services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $disableCacheBuster: '%image_loader.cache_buster.disabled%'

    imageloaderbundle.install.installer:
        class: ImageLoaderBundle\Install\Installer
        public: true

    imageloaderbundle.twig.extension:
        class: ImageLoaderBundle\Service\ImageLoaderTwigExtensions
        public: true
        tags:
            - { name: twig.extension }
