services:
  _defaults:
#    autowire: true
#    autoconfigure: true

  imageloaderbundle.install.installer:
    class: ImageLoaderBundle\Install\Installer
    public: true

  ImageLoaderBundle\Service\ImageLoaderTwigExtensions: ~
