services:

  imageloaderbundle.install.installer:
    class: ImageLoaderBundle\Install\Installer
    public: true

  imageloaderbundle.extensions.twig_extension:
    public: true
    class: ImageLoaderBundle\Service\ImageLoaderTwigExtensions
    tags: [ 'twig.extension' ]
