services:
    _defaults:
        autowire: true
        autoconfigure: true

    imageloaderbundle.install.installer:
        class: ImageLoaderBundle\Install\Installer
        public: true

    imageloaderbundle.twig.extension:
        class: ImageLoaderBundle\Service\ImageLoaderTwigExtensions
        public: true
        tags:
            - { name: twig.extension }
        arguments:
            $imageLoaderConfig: '%image_loader%'
